### PR TITLE
Try Go in Y Minutes

### PR DESCRIPTION
**Pull request by christophberger**
Hey @nalgeon, here is an early PR (draft mode) for Try Go, for tracking progress.

### CODE REVIEW

**Comment by nalgeon** [comment]
Looks good! Sorry, I accidentally removed the draft mode :)

**Comment by christophberger** [comment]
No probs, I switched back to draft mode ✍️

**Comment by nalgeon** [comment]
Nice! By the way, with the latest widget version (it's in the `main` branch) you don't need `output-mode="hidden"` anymore. If the output is empty, the snippet will display a short reassuring `ok` message.

**Comment by christophberger** [comment]
@nalgeon Finished! Please review and let me know if anything is wrong, weird, or missing.

**Comment by nalgeon** [comment]
Thanks a lot Christoph! Everything works fine, so I'll merge the PR, make a few edits and release the guide later today.

**Pull request merged**
