### PR TITLE
Add guide for Python3

### PR DESCRIPTION
**Pull request by juliusgeo**
Reformatted/slightly edited the guide here: https://learnxinyminutes.com/docs/python/.

### CODE REVIEW

**Comment by nalgeon** [comment]
Thank you for your work! Unfortunately there are some problems with the guide:

- Most of the code snippets are missing `print` to display the results.
- Many code snippets do not work because they depend on the previous snippets. You can fix this by using [templates](https://github.com/nalgeon/codapi-js/blob/main/docs/templates.md) and [code cells](https://github.com/nalgeon/codapi-js/blob/main/docs/code-cells.md).

All code snippets must work without errors for this PR to be accepted.

**Comment by juliusgeo** [comment]
@nalgeon Ahh, that makes sense. I can fix those issues, but I am running into trouble testing the `run` functionality because of `403 - Forbidden. Your domain is probably not allowed on Codapi.`. Is there any way that I can test this locally without spinning up my own codapi instance?

**Comment by nalgeon** [comment]
Do you follow the [guidelines](https://github.com/nalgeon/tryxinyminutes/blob/main/CONTRIBUTING.md)? `mkdocs serve` starts on `localhost:3000`, which is allowed on Codapi.

**Comment by juliusgeo** [comment]
Yes, running `mkdocs serve` is what I'm doing locally, but I am receiving this error:
```
INFO    -  Documentation built in 0.27 seconds
INFO    -  [08:57:24] Watching paths for changes: 'try', 'mkdocs.yml'
INFO    -  [08:57:24] Serving on http://127.0.0.1:3000/try/
INFO    -  [08:57:26] Browser connected: http://127.0.0.1:3000/try/python/
```

image

**Comment by nalgeon** [comment]
I see. Please use `http://localhost:3000/try/python/` instead of `http://127.0.0.1:3000/try/python/`.

**Comment by nalgeon** [comment]
Whenever you are ready :)

**Pull request closed without merging**
